name: Publish SemVer release
description: Creates GitHub releases, changelogs and tags the release
author: Henrique Cunha
inputs:
    github-token:
        required: true
        description: GitHub personal access token
runs:
    using: 'node16'
    main: 'dist/index.js'
