name: Publish SemVer release
description: Creates GitHub releases, changelogs and tags the release
author: Henrique Cunha
inputs:
    github-token:
        required: true
        description: GitHub personal access token
    git-committer-name:
        required: true
        description: Git committer name
        default: Publish SemVer release action
    git-committer-email:
        required: true
        description: Git committer email
        default: publish-semver@github.com
    release-candidate:
        required: false
        description: Determines if the release is a release candidate
        default: 'true'
    slack-webhook-url:
        required: false
        description: A webhook URL of a Slack channel that if provided, will notify the release
    discord-webhook-url:
        required: false
        description: A webhook URL of a Discord text channel that if provided, will notify the release
    project-url:
        required: false
        description: A URL of the project that will be used in the slack notification
    production-action-url:
        required: false
        description: A URL of the production deployment action that will be used in the slack notification
outputs:
    next-version:
        description: Next version to be released
    release-type:
        description: Type of release
runs:
    using: 'node16'
    main: 'dist/index.js'
